### ISSUE TITLE
Debt Planning - Student loans - Formulas

### ISSUE THREAD

**Issue by Brobin** [RaikesCohort2013/squad-hackathon-2015#2]
Research formulas needed to calculate debt over time.

**Comment by nleger67** [comment]
EMI = ( P × r × (1+r)n ) / ((1+r)n − 1)
EMI <- Estimated monthly installment
P <- Loan amount
r <- Monthly interest rate
n <- number of periods

**Comment by Brobin** [comment]
consolidated to #17
